# Generated by Django 4.0.5 on 2022-08-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={}, help_text='Enter your full name here', max_length=20)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('selected', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('subjects', models.CharField(choices=[('Math', 'Math'), ('English', 'English'), ('Hindi', 'Hindi'), ('Science', 'Science')], max_length=20)),
            ],
        ),
    ]
