# Generated by Django 4.0.5 on 2022-08-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.CharField(choices=[('Math', 'Math'), ('English', 'English'), ('Hindi', 'Hindi'), ('Science', 'Science')], default='Hello', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
    ]
