# Generated by Django 4.0.5 on 2022-07-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_section_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Math', 'Math'), ('Physics', 'Physics'), ('Social Science', 'Social Science'), ('Chemistry', 'Chemistry')], max_length=30)),
                ('student', models.ManyToManyField(related_name='subject', to='core.student')),
            ],
        ),
    ]
